version: '2.1'

networks:
  test-net:

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: /usr/local/bin/run_tests.sh
    networks:
      - test-net

  db:
    image: postgres:9.6
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backup_test
    volumes:
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-net
